### PR TITLE
Add ID to upsell notice for better javascript call

### PR DESCRIPTION
**Pull request by nicomollet**
Hello

I created this PR to fix the upsell notice, as explained in https://wordpress.org/support/topic/admin-nag/

Thank you

### CODE REVIEW

**Comment by mahdiyazdani** [comment]
@nicomollet Looks great, would you be able to have this updated to use CSS class name instead of ID?

**Comment by nicomollet** [comment]
@mahdiyazdani I could, can you explain why the class is better than ID in this case? I suggested ID because it has a better javascript performance.

**Comment by mahdiyazdani** [comment]
> why the class is better than ID in this case?

I believe it depends on how the browser indexes the elements internally.
In my tests, the class name approach was faster on chrome and IE, but roughly the same on FF. What this means is that Chrome and IE index elements based on the class name and FF mostly doesn't or does a poor job at it.

However, it is not a big deal though, we can leave it as-is for now if you prefer.

I will have this merged into the next release. Thank you for your contribution.

**Comment by nicomollet** [comment]
Thanks a lot @mahdiyazdani !

**Pull request merged**
